Repository Homerun-Ticket/Ticketable, pull requests merged in 2025-04, with the labels that each got.

#10 Spring Security 및 멤버 CRUD 구현
  src/main/java/com/example/ticketable/common/config/SecurityConfig.java
  src/main/java/com/example/ticketable/common/entity/Auth.java
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/ticketable/common/util/JwtAuthenticationToken.java
  src/main/java/com/example/ticketable/common/util/JwtUtil.java
  src/main/java/com/example/ticketable/domain/auth/controller/AuthController.java
  src/main/java/com/example/ticketable/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/example/ticketable/domain/auth/dto/request/SignupRequest.java
  src/main/java/com/example/ticketable/domain/auth/dto/response/AuthResponse.java
  src/main/java/com/example/ticketable/domain/auth/service/AuthService.java
  src/main/java/com/example/ticketable/domain/member/controller/MemberController.java
  src/main/java/com/example/ticketable/domain/member/dto/request/DeleteMemberRequest.java
  src/main/java/com/example/ticketable/domain/member/dto/request/UpdatePasswordRequest.java
  src/main/java/com/example/ticketable/domain/member/entity/Member.java
  src/main/java/com/example/ticketable/domain/member/repository/MemberRepository.java
  src/main/java/com/example/ticketable/domain/member/role/MemberRole.java
  src/main/java/com/example/ticketable/domain/member/service/MemberService.java
  src/main/resources/application-local.properties
Labels: ✨Feat 

#11 포인트 CRUD 및 포인트 사용, 환불, 충전 내역 조회
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/domain/auth/controller/AuthController.java
  src/main/java/com/example/ticketable/domain/auth/service/AuthService.java
  src/main/java/com/example/ticketable/domain/member/controller/MemberController.java
  src/main/java/com/example/ticketable/domain/member/entity/Member.java
  src/main/java/com/example/ticketable/domain/point/controller/PointController.java
  src/main/java/com/example/ticketable/domain/point/controller/PointHistoryController.java
  src/main/java/com/example/ticketable/domain/point/dto/request/AddPointRequest.java
  src/main/java/com/example/ticketable/domain/point/dto/response/PointHistoryResponse.java
  src/main/java/com/example/ticketable/domain/point/dto/response/PointResponse.java
  src/main/java/com/example/ticketable/domain/point/entity/Point.java
  src/main/java/com/example/ticketable/domain/point/enums/PointHistoryType.java
  src/main/java/com/example/ticketable/domain/point/repository/PointHistoryRepository.java
  src/main/java/com/example/ticketable/domain/point/repository/PointRepository.java
  src/main/java/com/example/ticketable/domain/point/service/PointHistoryService.java
  src/main/java/com/example/ticketable/domain/point/service/PointService.java
Labels: ✨Feat 

#12 경기장 CRUD, 구역 CRUD, 좌석 CRUD 구현
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/domain/stadium/controller/SeatController.java
  src/main/java/com/example/ticketable/domain/stadium/controller/SectionController.java
  src/main/java/com/example/ticketable/domain/stadium/controller/StadiumController.java
  src/main/java/com/example/ticketable/domain/stadium/dto/request/SeatCreateRequest.java
  src/main/java/com/example/ticketable/domain/stadium/dto/request/SeatUpdateRequest.java
  src/main/java/com/example/ticketable/domain/stadium/dto/request/SectionCreateRequest.java
  src/main/java/com/example/ticketable/domain/stadium/dto/request/SectionUpdateRequest.java
  src/main/java/com/example/ticketable/domain/stadium/dto/request/StadiumCreateRequest.java
  src/main/java/com/example/ticketable/domain/stadium/dto/request/StadiumUpdateRequest.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/SeatCreateResponse.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/SeatGetResponse.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/SeatUpdateResponse.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/SectionCreateResponse.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/SectionSeatCountResponse.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/SectionTypeSeatCountResponse.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/SectionUpdateResponse.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/StadiumCreateResponse.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/StadiumGetResponse.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/StadiumUpdateResponse.java
  src/main/java/com/example/ticketable/domain/stadium/entity/Seat.java
  src/main/java/com/example/ticketable/domain/stadium/entity/Section.java
  src/main/java/com/example/ticketable/domain/stadium/entity/Stadium.java
  src/main/java/com/example/ticketable/domain/stadium/repository/SeatRepository.java
  src/main/java/com/example/ticketable/domain/stadium/repository/SectionRepository.java
  src/main/java/com/example/ticketable/domain/stadium/repository/StadiumRepository.java
  src/main/java/com/example/ticketable/domain/stadium/service/SeatService.java
  src/main/java/com/example/ticketable/domain/stadium/service/SectionService.java
  src/main/java/com/example/ticketable/domain/stadium/service/StadiumService.java
  src/main/java/com/example/ticketable/domain/ticket/entity/Ticket.java
Labels: ✨Feat 

#15 ✨ Feat: 경기 CRUD 및 조회 쿼리에 경기 정보 추가
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/domain/game/controller/GameController.java
  src/main/java/com/example/ticketable/domain/game/dto/request/GameCreateRequest.java
  src/main/java/com/example/ticketable/domain/game/dto/request/GameUpdateRequest.java
  src/main/java/com/example/ticketable/domain/game/dto/response/GameCreateResponse.java
  src/main/java/com/example/ticketable/domain/game/dto/response/GameGetResponse.java
  src/main/java/com/example/ticketable/domain/game/dto/response/GameUpdateResponse.java
  src/main/java/com/example/ticketable/domain/game/entity/Game.java
  src/main/java/com/example/ticketable/domain/game/repository/GameRepository.java
  src/main/java/com/example/ticketable/domain/game/service/GameService.java
  src/main/java/com/example/ticketable/domain/stadium/controller/SeatController.java
  src/main/java/com/example/ticketable/domain/stadium/controller/SectionController.java
  src/main/java/com/example/ticketable/domain/stadium/controller/StadiumController.java
  src/main/java/com/example/ticketable/domain/stadium/repository/SeatRepository.java
  src/main/java/com/example/ticketable/domain/stadium/repository/SectionRepository.java
  src/main/java/com/example/ticketable/domain/stadium/repository/StadiumRepository.java
  src/main/java/com/example/ticketable/domain/stadium/service/SeatService.java
  src/main/java/com/example/ticketable/domain/stadium/service/SectionService.java
  src/main/java/com/example/ticketable/domain/stadium/service/StadiumService.java
Labels: ✨Feat 

#16 ✨ Feat: 예매로직 트랜잭션 분리 버전 추가, 좌석선점 버전 추가
  src/main/java/com/example/ticketable/common/exception/ServerException.java
  src/main/java/com/example/ticketable/common/util/SeatHoldRedisUtil.java
  src/main/java/com/example/ticketable/domain/game/entity/Game.java
  src/main/java/com/example/ticketable/domain/stadium/controller/SeatController.java
  src/main/java/com/example/ticketable/domain/stadium/dto/request/SeatHoldRequest.java
  src/main/java/com/example/ticketable/domain/stadium/service/SeatService.java
  src/main/java/com/example/ticketable/domain/ticket/controller/TicketController.java
  src/main/java/com/example/ticketable/domain/ticket/dto/TicketContext.java
  src/main/java/com/example/ticketable/domain/ticket/entity/Ticket.java
  src/main/java/com/example/ticketable/domain/ticket/repository/TicketSeatRepository.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketCreateService.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketPaymentService.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketPriceCalculator.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketSeatService.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketService.java
  src/main/resources/lua/checkHeldSeat.lua
  src/main/resources/lua/holdSeat.lua
  src/main/resources/lua/releaseSeat.lua
  src/test/resources/application-test.properties
Labels: ✨Feat , ♻️Refactor

#17 ✨ Feat: 경기, 경기장, 구역, 좌석 생성 및 수정 삭제 권한 추가
  src/main/java/com/example/ticketable/common/config/SecurityConfig.java
  src/main/java/com/example/ticketable/domain/game/service/GameService.java
  src/main/java/com/example/ticketable/domain/stadium/dto/request/SeatUpdateRequest.java
Labels: ✨Feat 

#18 ✨ Feat: 경기 취소 시 삭제 기능 추가
  src/main/java/com/example/ticketable/domain/auction/repository/AuctionRepository.java
  src/main/java/com/example/ticketable/domain/auction/service/AuctionService.java
  src/main/java/com/example/ticketable/domain/game/controller/GameController.java
  src/main/java/com/example/ticketable/domain/game/service/GameService.java
Labels: ✨Feat 

#19 ✨ Feat: S3 이미지 업로드 및 삭제 기능 구현
  build.gradle
  src/main/java/com/example/ticketable/common/config/S3Config.java
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/common/service/ImageService.java
  src/main/java/com/example/ticketable/domain/game/controller/GameController.java
  src/main/java/com/example/ticketable/domain/game/dto/request/GameCreateRequest.java
  src/main/java/com/example/ticketable/domain/game/service/GameService.java
  src/main/java/com/example/ticketable/domain/stadium/controller/StadiumController.java
  src/main/java/com/example/ticketable/domain/stadium/service/StadiumService.java
  src/main/resources/application-local.properties
Labels: ✨Feat 

#21 🐛 Bug : 티켓 예매 동시성 처리
  src/main/java/com/example/ticketable/common/config/LuaScriptConfig.java
  src/main/java/com/example/ticketable/common/util/SeatHoldRedisUtil.java
  src/main/java/com/example/ticketable/domain/game/controller/GameController.java
  src/main/java/com/example/ticketable/domain/game/service/GameService.java
  src/main/java/com/example/ticketable/domain/stadium/controller/SeatController.java
  src/main/java/com/example/ticketable/domain/stadium/service/SeatService.java
  src/main/java/com/example/ticketable/domain/ticket/controller/TicketController.java
  src/main/java/com/example/ticketable/domain/ticket/repository/TicketRepository.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketCreateService.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketService.java
  src/main/resources/lua/checkHeldSeat.lua
Labels: ♻️Refactor, 🐛 Bug

#26 PG사 연동 결제 시스템 구현
  build.gradle
  src/main/java/com/example/ticketable/common/config/IamPortConfig.java
  src/main/java/com/example/ticketable/common/config/SecurityConfig.java
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/ticketable/domain/auth/dto/request/SignupRequest.java
  src/main/java/com/example/ticketable/domain/auth/service/AuthService.java
  src/main/java/com/example/ticketable/domain/point/controller/PointAdminController.java
  src/main/java/com/example/ticketable/domain/point/controller/PointController.java
  src/main/java/com/example/ticketable/domain/point/controller/PointPaymentController.java
  src/main/java/com/example/ticketable/domain/point/dto/request/ExchangePointRequest.java
  src/main/java/com/example/ticketable/domain/point/dto/response/PointAdminResponse.java
  src/main/java/com/example/ticketable/domain/point/entity/Point.java
  src/main/java/com/example/ticketable/domain/point/entity/PointHistory.java
  src/main/java/com/example/ticketable/domain/point/entity/PointPayment.java
  src/main/java/com/example/ticketable/domain/point/enums/PointHistoryType.java
  src/main/java/com/example/ticketable/domain/point/repository/PointHistoryRepository.java
  src/main/java/com/example/ticketable/domain/point/repository/PointPaymentRepository.java
  src/main/java/com/example/ticketable/domain/point/service/PointAdminService.java
  src/main/java/com/example/ticketable/domain/point/service/PointHistoryService.java
  src/main/java/com/example/ticketable/domain/point/service/PointPaymentService.java
  src/main/java/com/example/ticketable/domain/point/service/PointService.java
  src/main/resources/application-local.properties
  src/main/resources/static/login.html
  src/main/resources/static/point-charge.html
Labels: ✨Feat 

#27 ♻️ Refactor : 좌석 점유 데이터 이벤트 방식으로 해제
  src/main/java/com/example/ticketable/common/config/LuaScriptConfig.java
  src/main/java/com/example/ticketable/common/event/SeatHoldReleaseEvent.java
  src/main/java/com/example/ticketable/common/event/listener/SeatHoldReleaseEventListener.java
  src/main/java/com/example/ticketable/common/util/SeatHoldRedisUtil.java
  src/main/java/com/example/ticketable/domain/ticket/controller/TicketController.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketCreateService.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketService.java
Labels: ♻️Refactor

#30 ✨ Feat : 대기열 기능 추가
  build.gradle
  src/main/java/com/example/ticketable/common/config/LuaScriptConfig.java
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/domain/queue/QueueSystemConstants.java
  src/main/java/com/example/ticketable/domain/queue/WaitingQueue.java
  src/main/java/com/example/ticketable/domain/queue/WaitingQueueAspect.java
  src/main/java/com/example/ticketable/domain/queue/controller/WaitingQueueController.java
  src/main/java/com/example/ticketable/domain/queue/dto/WaitingResponse.java
  src/main/java/com/example/ticketable/domain/queue/service/ProceedQueueService.java
  src/main/java/com/example/ticketable/domain/queue/service/QueueManager.java
  src/main/java/com/example/ticketable/domain/queue/service/RedisProceedQueueService.java
  src/main/java/com/example/ticketable/domain/queue/service/RedisWaitingQueueService.java
  src/main/java/com/example/ticketable/domain/queue/service/WaitingQueueService.java
  src/main/resources/lua/moveWaitingToProceed.lua
Labels: ✨Feat 

#31 ✨ Feat: 캐싱 기능 추가 및 쿼리 최적화
  build.gradle
  src/main/java/com/example/ticketable/common/config/CachingConfig.java
  src/main/java/com/example/ticketable/common/config/SecurityConfig.java
  src/main/java/com/example/ticketable/domain/game/controller/GameController.java
  src/main/java/com/example/ticketable/domain/game/entity/Game.java
  src/main/java/com/example/ticketable/domain/game/repository/GameRepository.java
  src/main/java/com/example/ticketable/domain/game/repository/GameRepositoryQuery.java
  src/main/java/com/example/ticketable/domain/game/repository/GameRepositoryQueryImpl.java
  src/main/java/com/example/ticketable/domain/game/service/GameCacheService.java
  src/main/java/com/example/ticketable/domain/game/service/GameService.java
  src/main/java/com/example/ticketable/domain/game/util/GameCacheHelper.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketCreateService.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketService.java
Labels: ✨Feat , ♻️Refactor

#33 🐛 Fix : 티켓 예매 관련 로직 수정
  src/main/java/com/example/ticketable/domain/game/repository/GameRepository.java
  src/main/java/com/example/ticketable/domain/stadium/service/SeatService.java
  src/main/java/com/example/ticketable/domain/stadium/service/SeatValidator.java
  src/main/java/com/example/ticketable/domain/ticket/controller/TicketController.java
  src/main/java/com/example/ticketable/domain/ticket/repository/TicketRepository.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketService.java
Labels: 🐛 Bug

#34 ♻️ Refactor : 대기열 코드 리팩토링
  src/main/java/com/example/ticketable/common/config/LuaScriptConfig.java
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/domain/queue/QueueSystemConstants.java
  src/main/java/com/example/ticketable/domain/queue/WaitingQueueAspect.java
  src/main/java/com/example/ticketable/domain/queue/controller/WaitingQueueController.java
  src/main/java/com/example/ticketable/domain/queue/dto/WaitingResponse.java
  src/main/java/com/example/ticketable/domain/queue/service/QueueManager.java
  src/main/java/com/example/ticketable/domain/queue/service/RedisProceedQueueService.java
  src/main/java/com/example/ticketable/domain/queue/service/RedisProceedQueueServiceV2.java
  src/main/java/com/example/ticketable/domain/queue/service/RedisWaitingQueueService.java
  src/main/resources/lua/moveWaitingToProceedV2.lua
Labels: ♻️Refactor

#37 서버 모니터링 기능 및 EC2 모니터링 서버 생성
  build.gradle
  docker/docker-compose.yml
  docker/prometheus.yml
  src/main/java/com/example/ticketable/common/config/SecurityConfig.java
  src/main/java/com/example/ticketable/domain/point/controller/PointPaymentController.java
  src/main/resources/application-local.properties
Labels: ✨Feat 

#35 Feat/auction 입찰가 조회 추가, 입찰 기능 리팩토링
  src/main/java/com/example/ticketable/common/util/AuctionBidRedisUtil.java
  src/main/java/com/example/ticketable/domain/auction/controller/AuctionController.java
  src/main/java/com/example/ticketable/domain/auction/dto/event/BidUpdateEvent.java
  src/main/java/com/example/ticketable/domain/auction/dto/request/AuctionBidRequest.java
  src/main/java/com/example/ticketable/domain/auction/dto/request/AuctionSearchCondition.java
  src/main/java/com/example/ticketable/domain/auction/dto/response/AuctionBidResponse.java
  src/main/java/com/example/ticketable/domain/auction/entity/Auction.java
  src/main/java/com/example/ticketable/domain/auction/entity/AuctionTicketInfo.java
  src/main/java/com/example/ticketable/domain/auction/repository/AuctionHistoryRepository.java
  src/main/java/com/example/ticketable/domain/auction/repository/AuctionRepository.java
  src/main/java/com/example/ticketable/domain/auction/repository/AuctionRepositoryQuery.java
  src/main/java/com/example/ticketable/domain/auction/repository/AuctionRepositoryQueryImpl.java
  src/main/java/com/example/ticketable/domain/auction/repository/AuctionTicketInfoRepository.java
  src/main/java/com/example/ticketable/domain/auction/repository/AuctionTicketInfoRepositoryQuery.java
  src/main/java/com/example/ticketable/domain/auction/repository/AuctionTicketInfoRepositoryQueryImpl.java
  src/main/java/com/example/ticketable/domain/auction/service/AuctionHistoryService.java
  src/main/java/com/example/ticketable/domain/auction/service/AuctionService.java
  src/main/java/com/example/ticketable/domain/auction/service/AuctionTicketInfoService.java
  src/main/java/com/example/ticketable/domain/auth/service/AuthService.java
  src/main/java/com/example/ticketable/domain/ticket/entity/Ticket.java
Labels: ✨Feat , ♻️Refactor

#38 ⚡️ Perf, ♻️ Refactor, 🐛 Fix : GAME 서비스의 GET 메서드 성능 개선 및 코드 리팩토링 및 버그 수정
  src/main/java/com/example/ticketable/common/config/CachingConfig.java
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/domain/game/controller/GameController.java
  src/main/java/com/example/ticketable/domain/game/entity/Game.java
  src/main/java/com/example/ticketable/domain/game/repository/GameRepository.java
  src/main/java/com/example/ticketable/domain/game/repository/GameRepositoryQuery.java
  src/main/java/com/example/ticketable/domain/game/repository/GameRepositoryQueryImpl.java
  src/main/java/com/example/ticketable/domain/game/service/GameCacheService.java
  src/main/java/com/example/ticketable/domain/game/service/GameService.java
  src/main/java/com/example/ticketable/domain/game/util/GameCacheHelper.java
  src/main/java/com/example/ticketable/domain/stadium/controller/SeatController.java
  src/main/java/com/example/ticketable/domain/stadium/dto/response/SeatGetResponse.java
  src/main/java/com/example/ticketable/domain/stadium/entity/Seat.java
  src/main/java/com/example/ticketable/domain/stadium/service/SeatService.java
  src/main/java/com/example/ticketable/domain/ticket/repository/TicketSeatRepository.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketSeatService.java
  src/main/java/com/example/ticketable/domain/ticket/service/TicketService.java
  src/test/java/com/example/ticketable/domain/game/service/GameServiceTest.java
  src/test/resources/application-test.properties
Labels: ♻️Refactor, 🐛 Bug

#41 ♻️ Refactor : Auth에서 role 검사, 클래스명과 메서드명 리팩터링
  src/main/java/com/example/ticketable/common/config/SecurityConfig.java
  src/main/java/com/example/ticketable/common/entity/Auth.java
  src/main/java/com/example/ticketable/common/exception/ErrorCode.java
  src/main/java/com/example/ticketable/domain/point/controller/PointAdminController.java
  src/main/java/com/example/ticketable/domain/point/controller/PointController.java
  src/main/java/com/example/ticketable/domain/point/controller/PointExchangeController.java
  src/main/java/com/example/ticketable/domain/point/controller/PointHistoryController.java
  src/main/java/com/example/ticketable/domain/point/dto/response/PointExchangeResponse.java
  src/main/java/com/example/ticketable/domain/point/dto/response/PointResponse.java
  src/main/java/com/example/ticketable/domain/point/service/PointExchangeService.java
  src/main/java/com/example/ticketable/domain/point/service/PointHistoryService.java
  src/main/java/com/example/ticketable/domain/point/service/PointService.java
Labels: ♻️Refactor
